spring.application.name=local-server-management

spring.jvm.arguments=--enable-native-access=ALL-UNNAMED

sprout.mcp.http.port=3001

spring.datasource.url=
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false